name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
          !~/.cache/vcpkg/*/buildtrees
          !~/.cache/vcpkg/*/packages
          !~/.cache/vcpkg/*/downloads
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure -C Debug

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
          D:\\a\\ParloPlusPlus\\ParloPlusPlus\\vcpkg_installed
          D:\\a\\ParloPlusPlus\\ParloPlusPlus\\vcpkg/downloads
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

    - name: Install dependencies
      run: |
        choco install -y cmake
        choco install -y ninja
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe integrate install
        .\vcpkg\vcpkg.exe install

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake -DCMAKE_MAKE_PROGRAM=C:/ProgramData/chocolatey/lib/ninja/tools/ninja.exe -D_WIN32_WINNT=0x0601
    
    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure -C Debug
